spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tutor_db
    username: postgres
    password: 9704
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 5000000000000MB
      max-request-size: 500000000000MB
server:
  port: 8081